project:
  type: website
  output-dir: docs

website:
  title: "Karl's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research Notes

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  cache: true

bibliography: 
  - library.bib




